[project]
name = "fundamentos-pandas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "LuisVilla97Go", email = "269536744+LuisVilla97Go@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pandas>=3.0.6",
]

[project.scripts]
fundamentos-pandas = "fundamentos_pandas:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.4.0",
]
